### ISSUE TITLE
Add sponsor logos

### ISSUE THREAD

**Issue by oliviabrown9** [TreeHacks/website-2019#5]
Waiting on @gtmtg to send logos and spec

**Comment by oliviabrown9** [comment]
Spec: https://treehacks.quip.com/pFAQAYyTHfMv/Logo-Spec

**Comment by theopolisme** [comment]
Do we have a folder with image assets?

**Comment by oliviabrown9** [comment]
Sponsorship team is working on collecting them. I'll ping you when we have them :)

**Comment by oliviabrown9** [comment]
Deadline: Feb 1 for all logos currently in repo.

**Comment by theopolisme** [comment]
Added in e2261914f0

Have marked missing logos in the quip

Do we want links to sites?

**Comment by theopolisme** [comment]
Also feeling quite iffy about the gcp logo...

**Comment by oliviabrown9** [comment]
Blocked on @gtmtg with https://treehacks.quip.com/pFAQAYyTHfMv/Logo-Spec

**Comment by oliviabrown9** [comment]
Also decision for links (and if yes, what links) is also @gtmtg
