### ISSUE TITLE
Set up redirects

### ISSUE THREAD

**Issue by oliviabrown9** [TreeHacks/website-2019#7]
- [x] Update slack.treehacks.com -> https://join.slack.com/t/treehacks-2019/shared_invite/enQtNTE5ODY0MDI2NjQ3LWI2YjhlYTU3OTE1ODcyMTdmZWYzYWVjY2NjNzQ2YTBiZDY5YWYwYzhkMDhlZTBmNmNmMzMzZWYxM2QwMTMxMmI

- [ ] Add treehacks.com/slack -> https://join.slack.com/t/treehacks-2019/shared_invite/enQtNTE5ODY0MDI2NjQ3LWI2YjhlYTU3OTE1ODcyMTdmZWYzYWVjY2NjNzQ2YTBiZDY5YWYwYzhkMDhlZTBmNmNmMzMzZWYxM2QwMTMxMmI

- [x] Update volunteer.treehacks.com -> https://goo.gl/forms/pZURr2kMSKwuFar42

- [ ] Add treehacks.com/volunteer -> https://goo.gl/forms/pZURr2kMSKwuFar42

**Comment by epicfaace** [comment]
Why do we need http://treehacks.com/slack ? Isn't http://slack.treehacks.com enough?

**Comment by oliviabrown9** [comment]
We need both bc people will accidentally type in one vs the other

**Comment by epicfaace** [comment]
I noticed that there's an existing DNS record for volunteers.treehacks.com -- would you like me to update it or remove it @oliviabrown9 ?
