### ISSUE TITLE
Update site to reflect that TreeHacks is over (for post TreeHacks 2019)

### ISSUE THREAD

**Issue by oliviabrown9** [TreeHacks/website-2019#9]
Bare minimum changes that should go live on the night of Feb. 18th :)

- [x] Change if statement content from apply/live to email sign up
- [x] Remove top right apply now button
- [x] Consider adding note under date saying "Thanks for a great 2019/stay tuned for 2020!" similar to last year
- [x] Change 2018 video to 2019 video

**Comment by theopolisme** [comment]
Still pending: need 2019 video
